version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"
    steps:
      - run:
          name: Build Success
          when: on_success
          command: |
            curl --user $CIRCLE_API_USER_TOKEN \
                  --data build_parameters[CIRCLE_JOB]=deploy_docker \
                  https://circleci.com/api/v1.1/project/github/Leitirion/My_ui_automation/tree/master
        
