version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.4.0-jessie
        environment:
          LANG: C.UTF-8
    steps:
      - deploy:
          name: conditionally run a deploy job
          command: |
              curl --user $CIRCLE_API_USER_TOKEN \
                  --data build_parameters[CIRCLE_JOB]=deploy_docker \
                  https://circleci.com/api/v1.1/project/github/Leitirion/My_ui_automation/tree/master

  deploy_docker:
    docker:
      - image: ruby:2.4.0-jessie
    steps:
      - setup_remote_docker